from figure_artifact_audit import audit_figure_artifacts, audit_to_dict


def _write_png(path, *, nonblank=True):
    import struct
    import zlib

    signature = b"\x89PNG\r\n\x1a\n"
    width, height = 2, 2
    color_type = 6
    bit_depth = 8
    ihdr = struct.pack("!IIBBBBB", width, height, bit_depth, color_type, 0, 0, 0)
    pixel = b"\xff\x00\x00\xff" if nonblank else b"\x00\x00\x00\x00"
    raw = b"".join(b"\x00" + pixel * width for _ in range(height))

    def chunk(kind, payload):
        crc = zlib.crc32(kind + payload) & 0xFFFFFFFF
        return struct.pack("!I", len(payload)) + kind + payload + struct.pack("!I", crc)

    path.write_bytes(signature + chunk(b"IHDR", ihdr) + chunk(b"IDAT", zlib.compress(raw)) + chunk(b"IEND", b""))


def _long_description() -> str:
    return (
        "Long description for demo figure.\n"
        "Reading order: title, encoded marks, caveat.\n"
        "Caveat: demo only.\n"
        "Evidence boundary: protocol metadata.\n"
    )


def test_figure_artifact_audit_scores_complete_registry(tmp_path):
    figure_dir = tmp_path / "figures"
    figure_dir.mkdir()
    long_dir = figure_dir / "long_descriptions"
    long_dir.mkdir()
    _write_png(figure_dir / "demo.png")
    (long_dir / "demo.md").write_text(_long_description())
    registry = [
        {
            "label": "fig:demo",
            "png": "output/figures/demo.png",
            "generator": "generate_demo",
            "description": "Demo figure.",
            "claim_status": "protocol",
            "caption_contract": "what the figure encodes",
            "section": "methods_protocol",
            "method_source_family": "shared_workspace",
            "accessibility_description": "Long description for demo figure.",
            "placement": "main",
            "long_description": "output/figures/long_descriptions/demo.md",
        }
    ]

    audit = audit_figure_artifacts(
        registry,
        figure_dir,
        "# Methods {#sec:methods_protocol}\n\n"
        "![Demo generated by `generate_demo()`.](../output/figures/demo.png){#fig:demo}\n\n"
        "See @fig:demo.",
    )

    assert audit.total_figures == 1
    assert audit.score == 1.0
    assert all(check.passed for check in audit.checks)
    assert {"readability_metadata", "long_description_reading_guidance"} <= {check.key for check in audit.checks}
    assert audit_to_dict(audit)["total_figures"] == 1


def test_figure_artifact_audit_fails_missing_file_and_reference(tmp_path):
    figure_dir = tmp_path / "figures"
    figure_dir.mkdir()
    registry = [
        {
            "label": "fig:demo",
            "png": "output/figures/demo.png",
            "generator": "generate_demo",
            "description": "Demo figure.",
            "claim_status": "conceptual",
            "caption_contract": "what the figure encodes",
            "section": "methods_protocol",
            "method_source_family": "shared_workspace",
            "accessibility_description": "Long description for demo figure.",
            "placement": "main",
            "long_description": "output/figures/long_descriptions/demo.md",
        }
    ]

    audit = audit_figure_artifacts(registry, figure_dir, "No figure reference here.")
    checks = {check.key: check.passed for check in audit.checks}

    assert checks["files_present"] is False
    assert checks["png_headers"] is False
    assert checks["labels_match_manuscript"] is False
    assert checks["long_descriptions_present"] is False
    assert audit.score < 1.0


def test_figure_artifact_audit_fails_orphan_png_and_invalid_status(tmp_path):
    figure_dir = tmp_path / "figures"
    figure_dir.mkdir()
    long_dir = figure_dir / "long_descriptions"
    long_dir.mkdir()
    _write_png(figure_dir / "demo.png")
    _write_png(figure_dir / "orphan.png")
    (long_dir / "demo.md").write_text(_long_description())
    registry = [
        {
            "label": "fig:demo",
            "png": "output/figures/demo.png",
            "generator": "generate_demo",
            "description": "Demo figure.",
            "claim_status": "empirical",
            "caption_contract": "what the figure encodes",
            "section": "methods_protocol",
            "method_source_family": "shared_workspace",
            "accessibility_description": "Long description for demo figure.",
            "placement": "main",
            "long_description": "output/figures/long_descriptions/demo.md",
        }
    ]

    audit = audit_figure_artifacts(
        registry,
        figure_dir,
        "# Methods {#sec:methods_protocol}\n\n"
        "![Demo generated by `generate_demo()`.](../output/figures/demo.png){#fig:demo}\n",
    )
    checks = {check.key: check.passed for check in audit.checks}

    assert checks["orphan_pngs_absent"] is False
    assert checks["claim_status_valid"] is False
    assert audit.score < 1.0


def test_figure_artifact_audit_fails_missing_readability_metadata(tmp_path):
    figure_dir = tmp_path / "figures"
    figure_dir.mkdir()
    long_dir = figure_dir / "long_descriptions"
    long_dir.mkdir()
    _write_png(figure_dir / "demo.png")
    (long_dir / "demo.md").write_text("Long description only.\n")
    registry = [
        {
            "label": "fig:demo",
            "png": "output/figures/demo.png",
            "generator": "generate_demo",
            "description": "Demo figure.",
            "claim_status": "protocol",
            "caption_contract": "what the figure encodes",
            "section": "methods_protocol",
            "method_source_family": "shared_workspace",
            "accessibility_description": "",
            "placement": "main",
            "long_description": "output/figures/long_descriptions/demo.md",
        }
    ]

    audit = audit_figure_artifacts(
        registry,
        figure_dir,
        "# Methods {#sec:methods_protocol}\n\n"
        "![Demo generated by `generate_demo()`.](../output/figures/demo.png){#fig:demo}\n\n"
        "See @fig:demo.",
    )
    checks = {check.key: check.passed for check in audit.checks}

    assert checks["readability_metadata"] is False
    assert checks["long_description_reading_guidance"] is False
    assert audit.score < 1.0


def test_sidecar_path_rejects_absolute_paths():
    from pathlib import Path

    import pytest

    from figure_artifact_audit import _sidecar_path

    with pytest.raises(ValueError):
        _sidecar_path(Path("output/figures"), "/etc/passwd")
    # Relative output/figures paths are still accepted.
    assert _sidecar_path(Path("output/figures"), "output/figures/long_descriptions/demo.md").name == "demo.md"


def test_png_parsing_edge_branches(tmp_path):
    import struct
    import zlib

    from figure_artifact_audit import _png_dimensions, _png_nonblank

    def make_png(ihdr: bytes, idat: bytes) -> bytes:
        def chunk(kind: bytes, payload: bytes) -> bytes:
            crc = zlib.crc32(kind + payload) & 0xFFFFFFFF
            return struct.pack("!I", len(payload)) + kind + payload + struct.pack("!I", crc)

        return b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr) + chunk(b"IDAT", idat) + chunk(b"IEND", b"")

    def write(name: str, data: bytes):
        path = tmp_path / name
        path.write_bytes(data)
        return path

    ihdr = struct.pack("!IIBBBBB", 2, 2, 8, 6, 0, 0, 0)
    good_idat = zlib.compress(b"\x00\xff\x00\x00\xff" * 2)

    # Valid PNG parses to dimensions and nonblank.
    assert _png_dimensions(write("good.png", make_png(ihdr, good_idat))) == (2, 2)
    assert _png_nonblank(write("good2.png", make_png(ihdr, good_idat))) is True

    # Missing file / truncated header -> None / False.
    assert _png_dimensions(tmp_path / "nope.png") is None
    assert _png_nonblank(write("trunc.png", b"\x89PNG\r\n\x1a\n\x00\x00")) is False

    # Non-8-bit depth and unknown color type -> treated as nonblank (True).
    deep = struct.pack("!IIBBBBB", 2, 2, 16, 6, 0, 0, 0)
    assert _png_nonblank(write("deep.png", make_png(deep, good_idat))) is True
    odd_color = struct.pack("!IIBBBBB", 2, 2, 8, 7, 0, 0, 0)
    assert _png_nonblank(write("odd.png", make_png(odd_color, good_idat))) is True

    # Missing IDAT -> not nonblank; corrupt zlib -> not nonblank.
    assert _png_nonblank(write("noidat.png", make_png(ihdr, b""))) is False
    assert _png_nonblank(write("corrupt.png", make_png(ihdr, b"not-zlib-data"))) is False

    # All-blank pixels -> not nonblank.
    blank_idat = zlib.compress(b"\x00\x00\x00\x00\x00" * 2)
    assert _png_nonblank(write("blank.png", make_png(ihdr, blank_idat))) is False
